// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uwqrdsddbplhkdkpcefw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV3cXJkc2RkYnBsaGtka3BjZWZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3ODQzMzUsImV4cCI6MjA2OTM2MDMzNX0.jsyXy7Nq1MdnWZmya-Kv52feEIph4m0jF8LBX8BAtr4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});